Repository piug-07/blogzen-OpenSource, pull requests merged in 2024-05, with the labels that each got.

#12 Fixed the Chatbot Position
  chatBot/style.css
Labels: Gssoc24

#107 Added Calender
  css/navbar.css
  index.html
  js/theme.js
Labels: Gssoc, level 3

#167 Calendar bg
  css/desktop_9.css
  index.html
Labels: Gssoc, level 2
