Repository piug-07/blogzen-OpenSource, pull requests merged in 2024-06, with the labels that each got.

#290 added footer
  footer.css
  footer.html
Labels: good first issue, Gssoc, level 1, GSSoC level 1

#191 fixed navbar bgcolor to black in dark mode
  js/theme.js
Labels: Gssoc, level 2, GSSoC level 2

#345 Added responsivness to the website
  css/navbar.css
  css/sec1.css
  css/sec2.css
  css/sec3.css
  index.html
Labels: bug, Gssoc, level 3

#472 added hovering effect to buttons
  css/sec1.css
  css/sec2.css
Labels: bug, enhancement, good first issue, Gssoc, level 3, GSSoc'24

#378 added hover effect to containers
  css/navbar.css
  css/sec2.css
  css/sec3.css
  index.html
Labels: enhancement, Gssoc, level 2, GSSoc'24

#494 login page
  1.png
  css/sec4.css
  index.html
  login.html
  login1.css
Labels: enhancement, Gssoc, level 3, GSSoc'24

#497 Fixed the issue #496
  css/desktop_9.css
  css/navbar.css
Labels: bug, Gssoc, level 2, GSSoc'24

#554 fix: Fix Image hover smoothness
  css/sec2.css
  css/sec3.css
Labels: good first issue, gssoc, level2, GSSoc'24
